name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.9.0
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: PaperMC
          base: master
          head: master
